import { stringify } from 'yaml';
import type { Config, Page, WidgetInstance } from '../model/types';
import type { ThemeConfig } from '../model/theme';
import { hslToString, isThemeEmpty } from '../model/theme';
import type { FieldDef, WidgetDef } from '../catalog/types';
import { lookup } from '../model/catalogSource';

const HEADER = [
  '# Generated by Glance Layout Builder.',
  '# Full property reference: https://github.com/glanceapp/glance/blob/main/docs/configuration.md',
  '',
].join('\n');

/**
 * Mirrors Glance's `titleToSlug` (internal/glance/utils.go): lowercase,
 * runs of whitespace become a single dash, leading/trailing dashes trimmed.
 */
export function slugify(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, '-').replace(/^-+|-+$/g, '');
}

/** True when a value carries no information and should be left out entirely. */
function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null) return true;
  if (typeof value === 'string') return value.trim() === '';
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === 'object') return Object.keys(value as object).length === 0;
  return false;
}

/** True when the value matches the catalog default, so Glance's own default covers it. */
function isDefault(field: FieldDef, value: unknown): boolean {
  // A required field must always be written out: Glance has no default to fall
  // back on, so omitting it fails validation.
  if ('required' in field && field.required) return false;

  switch (field.kind) {
    case 'number':
      return field.default !== undefined && value === field.default;
    case 'boolean':
      // Glance's zero value is false, so an explicit false is always redundant.
      return value === false || value === (field.default ?? false);
    case 'enum':
      return field.default !== undefined && value === field.default;
    default:
      return false;
  }
}

function coerce(field: FieldDef, value: unknown): unknown {
  if (field.kind === 'number' && typeof value === 'string') {
    const n = Number(value);
    return Number.isFinite(n) ? n : undefined;
  }
  return value;
}

/** Emits one object-list row, pruned against its own sub-field definitions. */
function emitObject(fields: FieldDef[], raw: unknown): Record<string, unknown> | undefined {
  if (typeof raw !== 'object' || raw === null) return undefined;
  const source = raw as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const field of fields) {
    const value = emitField(field, source[field.key]);
    if (value !== undefined) out[field.key] = value;
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

function emitField(field: FieldDef, rawValue: unknown): unknown {
  const value = coerce(field, rawValue);
  if (isEmpty(value) || isDefault(field, value)) return undefined;

  if (field.kind === 'stringList') {
    const items = (value as unknown[]).filter((v) => !isEmpty(v));
    return items.length > 0 ? items : undefined;
  }

  if (field.kind === 'objectList') {
    const rows = (value as unknown[])
      .map((row) => emitObject(field.fields, row))
      .filter((row): row is Record<string, unknown> => row !== undefined);
    return rows.length > 0 ? rows : undefined;
  }

  return value;
}

/**
 * Key order is `type`, `title`, the widget's own fields in catalog order, any
 * properties the catalog does not model, then nested `widgets`, then `cache`
 * last — the shape Glance's own docs use.
 */
function emitWidget(widget: WidgetInstance): Record<string, unknown> {
  const def: WidgetDef | undefined = lookup(widget.type);
  const out: Record<string, unknown> = { type: widget.type };

  const title = widget.props['title'];
  if (!isEmpty(title)) out['title'] = title;

  for (const field of def?.fields ?? []) {
    const value = emitField(field, widget.props[field.key]);
    if (value !== undefined) out[field.key] = value;
  }

  // Properties the curated catalog has no field for — everything on a pasted
  // widget beyond the handful we model, and anything a newer Glance accepts.
  // Without this they would be silently dropped and the export would not run.
  // Pruning is skipped deliberately: with no field definition there is no
  // default to compare against, so the only safe move is to pass them through.
  for (const [key, value] of Object.entries(widget.props)) {
    if (key === 'title' || key === 'cache' || key === 'type' || key in out) continue;
    if (def?.fields.some((field) => field.key === key)) continue;
    if (isEmpty(value)) continue;
    out[key] = value;
  }

  const children = (widget.children ?? []).map(emitWidget);
  if (children.length > 0) out['widgets'] = children;

  const cache = widget.props['cache'];
  if (!isEmpty(cache)) out['cache'] = cache;

  return out;
}

/**
 * Only properties the user actually set are written; anything left alone falls
 * through to Glance's own defaults. Key order follows `themeProperties`.
 */
function emitTheme(theme: ThemeConfig): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (theme.light) out['light'] = true;
  if (theme.backgroundColor) out['background-color'] = hslToString(theme.backgroundColor);
  if (theme.primaryColor) out['primary-color'] = hslToString(theme.primaryColor);
  if (theme.positiveColor) out['positive-color'] = hslToString(theme.positiveColor);
  if (theme.negativeColor) out['negative-color'] = hslToString(theme.negativeColor);
  if (theme.contrastMultiplier !== undefined) out['contrast-multiplier'] = theme.contrastMultiplier;
  if (theme.textSaturationMultiplier !== undefined) {
    out['text-saturation-multiplier'] = theme.textSaturationMultiplier;
  }
  return out;
}

function emitPage(page: Page): Record<string, unknown> {
  const out: Record<string, unknown> = { name: page.name };

  // Only write a slug when it differs from what Glance would derive anyway.
  if (!isEmpty(page.slug) && page.slug !== slugify(page.name)) out['slug'] = page.slug;
  if (page.width && page.width !== 'default') out['width'] = page.width;
  if (page.centerVertically) out['center-vertically'] = true;
  if (page.hideDesktopNavigation) out['hide-desktop-navigation'] = true;

  out['columns'] = page.columns.map((column) => ({
    size: column.size,
    widgets: column.widgets.map(emitWidget),
  }));

  return out;
}

/** Pure: the editor state in, a complete glance.yml out. */
export function toYaml(config: Config): string {
  return HEADER + stringify(toPlainObject(config), { lineWidth: 0, blockQuote: 'literal' });
}

/** The unprefixed document, for tests that compare against a parsed golden file. */
export function toPlainObject(config: Config): Record<string, unknown> {
  const doc: Record<string, unknown> = {};
  // `theme` first, matching the ordering used throughout the Glance docs.
  if (!isThemeEmpty(config.theme)) doc['theme'] = emitTheme(config.theme!);
  doc['pages'] = config.pages.map(emitPage);
  return doc;
}
